// <auto-generated />
namespace DeliveryServiceApp.CenteralDb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class firstMg_KitchenMapping : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstMg_KitchenMapping));
        
        string IMigrationMetadata.Id
        {
            get { return "201806250742406_firstMg_KitchenMapping"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
